---
name: 🎉 ShowCase Request
description: Add your Showcase from us! Your issue will reflected on Open-Set-Go.io's Showcase.
title: "🎉 [ShowCase request] - <title>"
labels: []
assignees: []

- type: input
  id: project_name
  attributes:
    label: "Project Name"
    description: Please enter your project name
    placeholder: ex. Open-Set-Go
  validations:
    required: true

- type: input
  id: owner-repo
  attributes:
    label: "Owner/Repository"
    description: Please enter the owner and repository name of the your showcase!
    placeholder: owner/repository (ex. AgainIoT/Open-Set-Go)
  validations:
    required: true

  - type: textarea
    id: screenshot
    attributes:
      label: "Project's main picture"
      description: Add screenshots to explain your project.
      value: |
        ![DESCRIPTION](LINK.png)
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: "Project Description"
      description: Please explain your project in Markdown syntax!.
    validations:
      required: true